#!/bin/bash

. "${OPENSHIFT_REPO_DIR}.openshift/config/tomcat.conf"

set -x

cd $OPENSHIFT_DATA_DIR

#Install tomcat if needed

if [[ -d ${TOMCAT_DIR_NAME} ]]; then
	echo "Tomcat ${TOMCAT_VERSION} already installed."
else
	for version in $TOMCAT_BASE-*; do 
		echo "Removing $version"
		rm -rf $version 
	done

	echo "Downloading Apache Tomcat v${TOMCAT_VERSION} ..."
	curl --insecure -o ${TOMCAT_DIR_NAME}.tar.gz "${TOMCAT_DOWNLOAD_URL}"
	tar -xf ${TOMCAT_DIR_NAME}.tar.gz
	rm -rf ${TOMCAT_DIR_NAME}.tar.gz
	echo "Installed Apache Tomcat v${TOMCAT_VERSION} . Home directory : ${OPENSHIFT_DATA_DIR}/${TOMCAT_DIR_NAME}"

    cd ${TOMCAT_DIR_NAME}
    #Set up server
    sed -ig 's/Server port="8005"/Server address="'$OPENSHIFT_DIY_IP'" port="15005"/g' conf/server.xml
    sed -ig 's/redirectPort="8443"/redirectPort="15443"/g' conf/server.xml
    sed -ig 's/Connector port/Connector address="'$OPENSHIFT_DIY_IP'" port/g' conf/server.xml
    sed -ig 's/port="8009"/port="15009"/g' conf/server.xml
    sed -ig 's/name="localhost"/name="'$OPENSHIFT_APP_DNS'"/' conf/server.xml
    sed -ig 's/defaultHost="localhost"/defaultHost="'$OPENSHIFT_DIY_IP'"/' conf/server.xml

    #Set up users
    sed -ig 's/<role rolename="manager-gui"\/>\n<user username="tomcat" password="tomcat" roles="manager-gui"\/>/<role rolename="manager-gui"\/>\n<user username="vincent" password="chan" roles="manager-gui"\/>\n/' conf/tomcat-users.xml
fi
